import { api } from "../../convex/_generated/api";
import { useAction } from "convex/react";
import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import { useSessionToken } from "~/useSessionToken";

export default function Home() {
  const session = useSession();
  const sessionToken = useSessionToken();

  const createTodo = useAction(api.actions.createTodo);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center dark:bg-gray-900 dark:text-white">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <button
            onClick={async () => {
              if (!sessionToken) return;
              console.log("we are here");
              await createTodo({ text: "hello world", sessionToken }).catch(
                console.error
              );
              console.log("gg");
            }}
          >
            Click Me
          </button>
          {session.data?.user.id}
          {session.data ? (
            <button onClick={() => signOut()}>Sign Out</button>
          ) : (
            <button onClick={() => signIn()}>Sign In</button>
          )}
        </div>
      </main>
    </>
  );
}
